In [ ]:
import pandas as pd

In [ ]:
data = {
'EmployeeID': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace', 'Henry', 'Ivy', 'Jack', 'Karen', 'Leo', 'Mona', 'Nina', 'Oscar'],
'Age': [45, 52, 37, 28, 41, 53, 32, 25, 48, 39, 29, 44, 33, 51, 36],
'Department': ['HR', 'IT', 'Finance', 'Marketing', 'Sales', 'IT', 'Finance', 'HR', 'Sales', 'Marketing', 'IT', 'Finance', 'HR', 'Sales', 'Marketing'],
'Salary': [54000, 78000, 66000, 72000, 85000, 90000, 62000, 40000, 94000, 70000, 65000, 86000, 47000, 88000, 56000]
}

In [ ]:
df = pd.DataFrame(data)

In [ ]:
print(df)

    EmployeeID     Name  Age Department  Salary
0            1    Alice   45         HR   54000
1            2      Bob   52         IT   78000
2            3  Charlie   37    Finance   66000
3            4    David   28  Marketing   72000
4            5      Eva   41      Sales   85000
5            6    Frank   53         IT   90000
6            7    Grace   32    Finance   62000
7            8    Henry   25         HR   40000
8            9      Ivy   48      Sales   94000
9           10     Jack   39  Marketing   70000
10          11    Karen   29         IT   65000
11          12      Leo   44    Finance   86000
12          13     Mona   33         HR   47000
13          14     Nina   51      Sales   88000
14          15    Oscar   36  Marketing   56000

In [ ]:
average_salary = df['Salary'].mean()

In [ ]:
print(average_salary)

   EmployeeID     Name  Age Department  Salary
0           1    Alice   45         HR   54000
1           2      Bob   52         IT   78000
2           3  Charlie   37    Finance   66000
3           4    David   28  Marketing   72000
4           5      Eva   41      Sales   85000

In [ ]:
median_salary = df['Salary'].median()

In [ ]:
print(median_salary)

70000.0

In [ ]:
std_dev_salary = df['Salary'].std()

In [ ]:
print(std_dev_salary)

16549.4928709527

In [ ]:
total_salary_expenditure = df['Salary'].sum()

In [ ]:
print(total_salary_expenditure)

1053000

In [ ]:
print("\n Basic Statistics:")

 Basic Statistics:

In [ ]:
print(f"Average Salary: ${average_salary}")

Average Salary: $   EmployeeID     Name  Age Department  Salary
0           1    Alice   45         HR   54000
1           2      Bob   52         IT   78000
2           3  Charlie   37    Finance   66000
3           4    David   28  Marketing   72000
4           5      Eva   41      Sales   85000

In [ ]:
print(f"Median Salary: ${median_salary}")

Median Salary: $70000.0

In [ ]:
print(f"Standard Deviation of Salaries: ${std_dev_salary}")

Standard Deviation of Salaries: $16549.4928709527

In [ ]:
print(f"Total Salary Expenditure: ${total_salary_expenditure}")

Total Salary Expenditure: $1053000